### ISSUE TITLE
Testing local stubs

### ISSUE THREAD

**Issue by hoefling** [typeddjango/pytest-mypy-plugins#17]
Hi, first of all, thank you for this project! Does `pytest-mypy-plugins` allow to test the local stubs? Supposing the project has the following structure:
```
root/
├──  src/
|   ├── foo/
|   |   └── __init__.py
|   └── ...
├── typeshed/
|   ├── bar/
|   |   └── __init__.pyi
|   └── baz.pyi
└── mypy.ini
```
with `mypy.ini` setting:
```ini
[mypy]
files = src/
mypy_path = typeshed/
...
```
I can't figure out how to pass this setting to the tests. AFAICT the tests are ran in a temporary directory, so a relative `mypy_path` will resolve against this temp dir, so only absolute paths would do. The `--mypy-testing-base` doesn't help either, raising on missing temporary directory (however, this may also emerge because I have misconfigured something):

```
Traceback (most recent call last):
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/_pytest/runner.py", line 237, in from_call
    result = func()
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/_pytest/runner.py", line 210, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/_pytest/runner.py", line 134, in pytest_runtest_call
    item.runtest()
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/pytest_mypy/item.py", line 219, in runtest
    mypy_cmd_options = self.prepare_mypy_cmd_options(execution_path)
  File "/home/hoefling/projects/.venvs/typeshed-py36/lib/python3.6/site-packages/pytest_mypy/item.py", line 285, in prepare_mypy_cmd_options
    with mypy_config_file_path.open('w') as f:
  File "/usr/lib64/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib64/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib64/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'pytest-mypy-u4fvf1rh/mypy.ini'
```

**Comment by sobolevn** [comment]
Thanks a lot for the report!

Looks like we have to implement a support for this! 
Any help is appreciated.

**Comment by MiroFurtado** [comment]
This issue also is relevant for testing local plugins. Right now, using a work-around that involves a bash script generating the mypy.ini for the particular environment, but this is non-ideal!

**Comment by sobolevn** [comment]
@MiroFurtado local plugins work quite well for me: https://github.com/dry-python/returns/blob/master/setup.cfg#L106

Can you please post your setup?

**Comment by MiroFurtado** [comment]
> Can you please post your setup?

@sobolevn Ah I see. Is there any way to test using a plugin that is local to your folder? ie. I include a relative path in the mypy.ini?

**Comment by ze-phyr-us** [comment]
I am struggling to run tests using a local plugin too. The only thing that works for me is to set the PYTHONPATH env variable **and** to use the `--mypy-same-process` flag:

```
PYTHONPATH=. pytest --mypy-same-process --mypy-ini-file=mypy.ini ...
```

Running the test in a subprocess doesn't work because pytest-mypy-plugins overwrites the PYTHONPATH variable: https://github.com/typeddjango/pytest-mypy-plugins/blob/master/pytest_mypy_plugins/item.py#L177

**Comment by sobolevn** [comment]
@ze-phyr-us any ideas how can  we fix it?

**Comment by hoefling** [comment]
@sobolevn one idea would be invoking `mypy` as a module e.g. replace
```python
subprocess.run([mypy_executable, *mypy_cmd_options])
```
with
```python
subprocess.run([sys_executable, '-m', 'mypy', *mypy_cmd_options])
```

**Comment by ze-phyr-us** [comment]
> @ze-phyr-us any ideas how can we fix it?

I haven't tried invoking mypy as a module. But my first idea was to not clobber `PYTHONPATH` completely but rather just _add_ the new directory (`execution_path`) to it. That way the user can always control their path using this standard variable.

Another difference between subprocess vs same process seems to be that the subprocess invocation doesn't pass any of the existing environment variables to the subprocess - only the variables explicitly set in the yaml test are passed. The same-process invocation naturally does preserve all variables. It would be nice if the same worked in the subprocess, so I could set my PYTHONPATH in the shell rather than in the yaml.

**Comment by sobolevn** [comment]
Sounds reasonable! 👍

**Comment by sobolevn** [comment]
Ok, I have introduced a new feature to merge existing `PYTHONPATH` and `MYPYPATH` env vars, see #157

**Comment by ze-phyr-us** [comment]
Sorry I forgot to reply in August 🤦  

Thank you for your work. I tried 1.5.0 and it works, with a caveat. When using a subprocess I cannot set `PYTHONPATH=.` as usual because the process is run in a temporary directory. So it's necessary to run `PYTHONPATH=$(pwd) pytest ...`. Perhaps it's worth mentioning this in the readme?

**Comment by sobolevn** [comment]
@ze-phyr-us yes, please!

**Comment by stdedos** [comment]
If you can install your stubs using `pip install .` (or equivalent), it also works.

**NB**: Do **not** use `--editable`, it doesn't work (as of now, not documented anywhere)

... which makes it hard for a REPL, and the `PYTHONPATH=$(pwd) pytest ...` might work better
